name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: composer update --no-dev 
    - uses: overtrue/phplint@7.4
    - name: check with exclude option
      with:
        path: .
        options: --exclude=*.log --exclude=vendor

    - uses: overtrue/phplint@7.4
    - name: check without exclude option
      with:
        path: .
